{% set version = "1.0.3" %}
  {% set name = "rsaccharis" %}
  {% set build_number = 0%}
  {% set filehash = "31ABF1D2D8636E1D3517CD837E95AFD925B51309AE7983ED8A462C9BC80378E8"%}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url:
    - 'https://github.com/saccharis/rsaccharis/releases/download/{{ version }}/rsaccharis_{{ version }}.tar.gz'
  sha256: {{ filehash|lower}}

build:
  noarch: generic
  number: {{ build_number }}
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base
    - r-jsonlite
    - r-ape
    - r-stringr
    - r-magicfor
    - r-knitr
    - r-dplyr
    - r-magrittr
    - r-rcolorbrewer
    - r-ggnewscale
    - r-ggplot2
    - bioconductor-ggtree

test:
  commands:
#    - 'R -e "library(''{{ name }}'')"'
#    - 'Rscript  "library(rsaccharis)"'

about:
  home: 'https://github.com/saccharis/rsaccharis'
  license: 'GPL 3'
  summary: 'A rendering package for creating phylogenetic trees from SACCHARIS .json and .tree files, in the R statistical computing language.'
  description: 'This package will use metadata .json and .tree files output from SACCHARIS v2 to generate annotated phylogenetic tree PDF files.
    Highly customizable, as the formatting of the tree is done using ggplot2. Of course plotting functions can easily be manipulated as desired.
    To use, call A_load_data() and B_plots_all() and follow prompts. Our default plots used for publication are domain_ECno_numeric.'
  license_file: LICENSE.md
