#'@title Plotting
#'
#' @description Generate circular plots of trees generated by SACCAHRIS v2. REQUIRED: run A_load_data() first.
#'
#' @param out_dir Directory to write rendered graph files to. If not given, defaults to working directory.
#'
#' @importFrom dplyr n_distinct count distinct
#' @importFrom RColorBrewer brewer.pal display.brewer.all
#' @importFrom ggnewscale new_scale_fill
#' @importFrom ggplot2 scale_colour_manual guides guide_legend ggsave geom_point aes scale_fill_manual
#' @importFrom ggtree ggtree geom_tiplab geom_rootedge geom_treescale theme gheatmap
#' @importFrom grDevices colorRampPalette
#' @importFrom graphics pie
#'
#' @export

B_plots_all <- function(out_dir=getwd()) {
  if (!exists("myTREE", inherits = TRUE)) {
    stop("myTREE is not defined, run A_load_data() first!")
  }
  if (!exists("tree_tip_names", inherits = TRUE)) {
    stop("tree_tip_names is not defined, run A_load_data() first!")
  }
  
  setwd(out_dir)
  #### basic tree ####
  p=ggtree(myTREE, layout="circular", size=0.5) +
    geom_tiplab(size=1.5, color="black") +
    geom_rootedge(rootedge = 0.2) +
    geom_treescale(x=-1, offset=1.5, width=0.5, color='darkblue', fontsize=2) +
    theme(legend.position="none")

  #Basic_tree
  ggsave("Basic_circular_tree.pdf", width = 30, height = 30, units = "cm", limitsize = 0.4)

  #### Basic circular tree with  bootstrap ####

  # bootstrap colours dots on node, in ranges
  a=nrow(tree_tip_names)
  b <- c(rep(NA,a), as.numeric(myTREE$node.label)*100)
  col <- cut(b, breaks=c(0,50,75,90,99,100))
  col <- factor(col, levels=rev(levels(col)))
  # prevent erroring out if there are fewer than 5 labels to change in the legend. NOTE this is not a perfect fix and may need a manual run
  if (dplyr::count(distinct(as.data.frame(col)))>=6) {
    col <- factor(col, labels=c("100%","91-99%","76-90%","51-75%","0-50%")) }

  # plot
  p1=ggtree(myTREE, layout="circular", size=0.5) +
    geom_tiplab(size=1.5, color="black") +
    geom_rootedge(rootedge = 0.2) +
    geom_point(aes(color=col), alpha=1, size=1.5, show.legend = TRUE) +
    geom_treescale(x=-1, offset=1.5, width=0.5, color='darkblue', fontsize=4) +
    theme(legend.position="bottom")+
    scale_colour_manual(na.translate = F, name="Bootstrap support",
                        values=c("#80b1d3","#8dd3c7","#fdc086","#bebada","#fb8072")) +
    guides(color = guide_legend(override.aes = list(size = 5)))

  ggsave("basic_circular_tree_bootstrap.pdf", width = 30, height = 30, units = "cm", limitsize = 0.4)


  #### Basic circular tree with coloured ring for domain  ####

  # second arrange database for colouring plot so that domain has unique numbers for factors.
  df_for_tree2 <<- (df_for_tree)
  df_for_tree2$domain <- factor(df_for_tree2$domain, levels=unique(df_for_tree2$domain))
  df_for_tree2$domain <- as.factor(df_for_tree2$domain)
  rownames(df_for_tree2) <- myTREE$tip.label

  # first organize colour scale for domain
  colourCount_do = dplyr::n_distinct(df_for_tree2$domain)
  plot_palette = colorRampPalette(RColorBrewer::brewer.pal(6, "Set2"))
  Phylo_col_do=plot_palette(colourCount_do)
  #palette(Phylo_col)
  pie(rep(1, colourCount_do), col=Phylo_col_do) # pie plot to check colors


  #third plot basic tree and add ring for domain
  p1=ggtree(myTREE, layout="circular", size=0.5) +
    geom_tiplab(size=1.5, color="black") +
    geom_rootedge(rootedge = 0.2) +
    geom_treescale(x=-1, offset=2, width=0.25, color='darkblue', fontsize=2) +
    theme(legend.position="none")

  p2=gheatmap(p1, df_for_tree2[, "domain", drop=F], offset=1.5, width=.05, hjust=0,
              colnames = FALSE, colnames_offset_y = .25, color="black", legend_title = "Domain") +
    scale_fill_manual("Domain", values=Phylo_col_do)

  plot(p2)

  ggsave("basic_circular_with_domain.pdf", width = 30, height = 30, units = "cm", limitsize = 0.4)


  #### Basic circular tree with coloured ring for domain and bootstrap values  ####

  p3=ggtree(myTREE, layout="circular", size=0.5) +
    geom_tiplab(size=1.5, color="black") +
    geom_rootedge(rootedge = 0.2) +
    geom_point(aes(color=col), alpha=1, size=1.5, show.legend = TRUE) +
    geom_treescale(x=-1, offset=1.5, width=0.5, color='darkblue', fontsize=4) +
    theme(legend.position="bottom")+
    scale_colour_manual(na.translate = F, name="Bootstrap support",
                        values=c("#80b1d3","#8dd3c7","#fdc086","#bebada","#fb8072")) +
    guides(color = guide_legend(override.aes = list(size = 5)))

  p4=gheatmap(p3, df_for_tree2[, "domain", drop=F], offset=1.5, width=.05, hjust=0,
              colnames = FALSE, colnames_offset_y = .25, color="black", legend_title = "Domain")+
    scale_fill_manual("Domain", values=Phylo_col_do)

  plot(p4)

  ggsave("basic_circular_domain_bootstrap.pdf", width = 30, height = 30, units = "cm", limitsize = 0.4)


  #### Basic circular tree with coloured ring for domain and ECno  ####

  # first arrange database for colouring plot so that ECno has unique numbers for factors.
  df_for_tree2$ec_num <- factor(df_for_tree2$ec_num, levels=unique(df_for_tree2$ec_num))
  df_for_tree2$ec_num <- as.factor(df_for_tree2$ec_num)

  # second colours for ECno
  colourCount_ec = dplyr::n_distinct(df_for_tree2$ec_num)
  plot_palette = colorRampPalette(RColorBrewer::brewer.pal(12, "Paired"))
  ECNo_col=plot_palette(colourCount_ec)
  #palette(Phylo_col)
  pie(rep(1, colourCount_ec), col=ECNo_col) # pie plot to check colours

  p6=ggtree(myTREE, layout="circular", size=0.5) +
    geom_tiplab(size=1.5, color="black") +
    geom_rootedge(rootedge = 0.2) +
    geom_treescale(x=-1, offset=1.5, width=0.5, color='darkblue', fontsize=4) +
    theme(legend.position="none")

  p7=gheatmap(p6, df_for_tree2[, "domain", drop=F], offset=0.4, width=.1, hjust=0,
              colnames = FALSE, colnames_offset_y = .25, color="black", legend_title = "Domain")+
    scale_fill_manual("Domain", values=Phylo_col_do)

  p8<- p7 + ggnewscale::new_scale_fill()

  p9=gheatmap(p8, df_for_tree2[, "ec_num", drop=F], offset=2, width=0.1, hjust=0,
              colnames = FALSE, colnames_offset_y = .25, color="black", legend_title = "ECNo")+
    scale_fill_manual("ECNo", values=ECNo_col)

  plot(p9)

  ggsave("basic_circular_domain_ECNo.pdf", width = 30, height = 30, units = "cm", limitsize = 0.4)



  ##### Numbered plots #####

  # first colours for Domain
  colourCount = dplyr::n_distinct(df_for_tree$domain)
  plot_palette = colorRampPalette(RColorBrewer::brewer.pal(6, "Set2"))
  Phylo_col=plot_palette(colourCount)
  #palette(Phylo_col)
  pie(rep(1, colourCount), col=Phylo_col) # pie plot to check colours

  # second colours for ECno
  colourCount_ec = dplyr::n_distinct(df_for_tree$ec_num)
  plot_palette = colorRampPalette(RColorBrewer::brewer.pal(12, "Paired"))
  ECNo_col=plot_palette(colourCount_ec)
  #palette(Phylo_col)
  pie(rep(1, colourCount_ec), col=ECNo_col) # pie plot to check colours

  # first arrange database for colouring plot so that ECno has unique numbers for factors
  df_for_tree$ec_num <- factor(df_for_tree$ec_num, levels=unique(df_for_tree$ec_num))
  df_for_tree$ec_num <- as.factor(df_for_tree$ec_num)


  #### Basic circular tree with 2 coloured rings for domain and ECno  ####

  df_for_tree$domain <- factor(df_for_tree$domain, levels=unique(df_for_tree$domain))
  df_for_tree$domain <- as.factor(df_for_tree$domain)
  myTREE2 <- myTREE
  myTREE2$tip.label <- rownames(df_for_tree)
  myTREE2$tip.label
  #myTREE2$tip.label<-as.factor(myTREE2$tip.label)

  # third plot basic tree and add ring for domain
  p10=ggtree(myTREE2, layout="circular", size=0.5) +
    geom_tiplab(size=1.5, color="black", offset=5, align=TRUE, linesize=.05) +
    geom_rootedge(rootedge = 0.2) +
    geom_treescale(x=-1, offset=2, width=0.25, color='darkblue', fontsize=2) +
    theme(legend.position="none")

  p11=gheatmap(p10, df_for_tree[, "domain", drop=F], offset=0.4, width=.1, hjust=0,
               colnames = FALSE, colnames_offset_y = .25, color="black", legend_title = "Domain")+
    scale_fill_manual("Domain", values=Phylo_col)

  p12<- p11 + ggnewscale::new_scale_fill()

  ## NOTE for p13: the offset value may need to be adjusted manually depending on the size of the tree
  p13=gheatmap(p12, df_for_tree[, "ec_num", drop=F], offset=1.4, width=0.1, hjust=0,
               colnames = FALSE, colnames_offset_y = .25, color="black", legend_title = "ECNo")+
    scale_fill_manual("ECNo", values=ECNo_col)

  plot(p13)

  ggsave("basic_circular_domain_ECno_numeric.pdf", width = 30, height = 30, units = "cm", limitsize = 0.4)

}
