#'@title Helper function for ease of calling from CLI
#'
#' @description Generate circular plots of trees generated by SACCAHRIS v2. REQUIRED: Input .json and .tree files generated by SACCHARIS 2
#'
#' @importFrom rsaccharis A_load_data
#' @importFrom rsaccharis B_plots_all
#'
#' @export

C_load_and_plot_all <- function(input_json, input_tree, output_folder) {
    data_folder <- basename(input_json)
    if (!isDir(data_folder)) {
        data_folder <- getwd()
    }
    setwd(data_folder)
    A_load_data(input_json, input_tree, out_dir)
    B_plots_all(output_folder)
}