#'@title Helper function for ease of calling from CLI
#'
#' @description Generate circular plots of trees generated by SACCAHRIS v2. REQUIRED: Input .json and .tree files generated by SACCHARIS 2 and output folder
#' 
#' @param input_json Argument for text filepath to metadata .json file name (SACCHARIS output).
#' @param input_tree Argument for text filepath to .tree file name (SACCHARIS output).
#' @param output_folder Argument for text folderpath output CAZY_TABLE_FINAL_GHxx_characterized_DATE.xlsx to.
#'
#' @export

C_load_and_plot_all <- function(input_json, input_tree, output_folder, root=NULL) {
    data_folder <- basename(input_json)
    if (!dir.exists(data_folder)) {
        data_folder <- getwd()
    }
    setwd(data_folder)
    rsaccharis::A_load_data(input_json, input_tree, output_folder, root)
    rsaccharis::B_plots_all(output_folder)
}